ch:
  diyamane:
    app:
      petrol:
        initData: true
logging:
  level:
    '*': INFO
    ch:
      diyamane:
        app:
          petrol: INFO
    org:
      springframework:
        boot:
          autoconfigure:
            logging:
              ConditionEvaluationReportLoggingListener: INFO
        security: TRACE
        security.oauth2: DEBUG


spring:
  mvc:
    favicon:
      enabled:false
  flyway:
    enabled: false
  jpa:
    show-sql: true
  application:
    name: petrol-business-resource
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081
server:
  port: 8085

springdoc:
  show-actuator: true
  swagger-ui:
    path: /petrol-api-ui.html

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true

management:
  endpoints:
    web:
      exposure:
        include: '*, openapi, swaggerui'