language: java
sudo: false
dist: trusty

before_script:
  - unset -v _JAVA_OPTIONS
  - wget https://github.com/sormuras/bach/raw/master/install-jdk.sh

services:
  - docker

jobs:
  include:
    - stage: Zulu-Install
      env: JDK=zulu17.32.13-ca-jdk17.0.2
      script: source install-jdk.sh --url https://cdn.azul.com/zulu/bin/zulu17.32.13-ca-jdk17.0.2-linux_x64.tar.gz

jdk: zulujdk17
script:
  - mvn install -DskipTests=false -Dmaven.javadoc.skip=true -B -V
  - cd petrol-app
  - pwd
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  
after_sucess:
  -  docker build -t deepak1947/petrol-app -f ./Dockerfile .
  -  docker push deepak1947/petrol-app
