sudo: required
language: java

services:
  - docker

script:
  - mvn install -DskipTests=false -Dmaven.javadoc.skip=true -B -V
  - cd petrol-app
  - pwd
  
after_sucess:
    docker build -t deepak1947/petrol-app -f ./Dockerfile .
