sudo: required
language: java
jdk: oraclejdk8

services:
  - docker

script:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
  - bash petrol-cicd/change-directory-petrol-app.sh
  
after_sucess:
    docker build -t deepak1947/petrol-app -f Dockerfile .
