sudo: required
language: java

services:
  - docker

script:
  - mvn install -DskipTests=false -Dmaven.javadoc.skip=true -B -V
  - cd petrol-app
  - pwd
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  
after_sucess:
  -  docker build -t deepak1947/petrol-app -f ./Dockerfile .
  -  docker push deepak1947/petrol-app
