apiVersion: v1
kind: Service
metadata:
  name: petrol-node-port
  labels:
    app: petrol-node-bec-port
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    component: petrol-app-backend
