CREATE TABLE CLIENT (
    ID varchar(255) NOT NULL,
    CLIENT_ID varchar(255) NOT NULL,
    CLIENT_ID_ISSUED_AT timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CLIENT_SECRET varchar(255) DEFAULT NULL,
    CLIENT_SECRET_EXPIRES_AT timestamp DEFAULT NULL,
    CLIENT_NAME varchar(255) NOT NULL,
    CLIENT_AUTHENTICATION_METHODS varchar(1000) NOT NULL,
    AUTHORIZATION_GRANT_TYPES varchar(1000) NOT NULL,
    REDIRECT_URIS varchar(1000) DEFAULT NULL,
    SCOPES varchar(1000) NOT NULL,
    CLIENT_SETTINGS varchar(2000) NOT NULL,
    TOKEN_SETTINGS varchar(2000) NOT NULL,
    PRIMARY KEY (ID)
);


CREATE TABLE CLIENT_AUTHORIZATION (
    ID varchar(255) NOT NULL,
    REGISTERED_CLIENT_ID varchar(255) NOT NULL,
    PRINCIPAL_NAME varchar(255) NOT NULL,
    AUTHORIZATION_GRANT_TYPE varchar(255) NOT NULL,
    ATTRIBUTES varchar(4000) DEFAULT NULL,
    STATE varchar(500) DEFAULT NULL,
    AUTHORIZATION_CODE_VALUE varchar(4000) DEFAULT NULL,
    AUTHORIZATION_CODE_ISSUED_AT timestamp DEFAULT NULL,
    AUTHORIZATION_CODE_EXPIRES_AT timestamp DEFAULT NULL,
    AUTHORIZATION_CODE_METADATA varchar(2000) DEFAULT NULL,
    ACCESS_TOKEN_VALUE varchar(4000) DEFAULT NULL,
    ACCESS_TOKEN_ISSUED_AT timestamp DEFAULT NULL,
    ACCESS_TOKEN_EXPIRES_AT timestamp DEFAULT NULL,
    ACCESS_TOKEN_METADATA varchar(2000) DEFAULT NULL,
    ACCESS_TOKEN_TYPE varchar(255) DEFAULT NULL,
    ACCESS_TOKEN_SCOPES varchar(1000) DEFAULT NULL,
    REFRESH_TOKEN_VALUE varchar(4000) DEFAULT NULL,
    REFRESH_TOKEN_ISSUED_AT timestamp DEFAULT NULL,
    REFRESH_TOKEN_EXPIRES_AT timestamp DEFAULT NULL,
    REFRESH_TOKEN_METADATA varchar(2000) DEFAULT NULL,
    OIDC_ID_TOKEN_VALUE varchar(4000) DEFAULT NULL,
    OIDC_ID_TOKEN_ISSUED_AT timestamp DEFAULT NULL,
    OIDC_ID_TOKEN_EXPIRES_AT timestamp DEFAULT NULL,
    OIDC_ID_TOKEN_METADATA varchar(2000) DEFAULT NULL,
    OIDC_ID_TOKEN_CLAIMS varchar(2000) DEFAULT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE AUTHORIZATION_CONSENT (
    REGISTERED_CLIENT_ID varchar(255) NOT NULL,
    PRINCIPAL_NAME varchar(255) NOT NULL,
    AUTHORITIES varchar(1000) NOT NULL,
    PRIMARY KEY (REGISTERED_CLIENT_ID, PRINCIPAL_NAME)
);

