CREATE TABLE USER (
     ID INTEGER NOT NULL auto_increment,
    USER_NAME varchar2(20) NOT NULL,
    PASSWORD varchar(120) DEFAULT NULL,
    EMAIL varchar(50) NOT NULL,
    PRIMARY KEY (ID)
);

ALTER TABLE USER
  ADD  CONSTRAINT UK_UserName UNIQUE (USER_NAME);

ALTER TABLE USER
  ADD  CONSTRAINT UK_Email UNIQUE (EMAIL);

CREATE TABLE ROLE (
    ID INTEGER NOT NULL auto_increment,
    NAME varchar2(20) NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE USER_ROLE (
    ID INTEGER NOT NULL auto_increment,
    USER_ID INTEGER NOT NULL,
    ROLE_ID INTEGER NOT NULL,
    PRIMARY KEY (ID),
    CONSTRAINT FK_USER
        FOREIGN KEY (USER_ID)
        REFERENCES USER(ID),
    CONSTRAINT FK_ROLE
        FOREIGN KEY (ROLE_ID)
        REFERENCES ROLE(ID)

);
